### ISSUE TITLE
Training Dialogue Issues (Sakura Bakushin O)

### ISSUE THREAD

**Issue by PIXIS39** [Hachimi-Hachimi/tl-en#1]
Issue with Sakura Bakushin O's training dialogues (most if not all of them):
   - [ ] Dialogue is off by one line, causing lines to be attributed to the wrong characters + the final line of the dialogue is in Japanese

**Comment by LeadRDRK** [comment]
Please attach at least one screenshot with a full dialogue line that I can use to the track down that specific story, and also, create a new issue for each story section.

A lot of story translations are missing from umamusu-translate because they were machine translated. I've opted to not include any of them due to the low quality translations. If you see spot one of them still left in there, please also create an issue for it!

**Comment by PIXIS39** [comment]
Gotcha - I wasn't going to request any new translations, just thought that some stuff that was already translated was missing. I didn't realize the MTL stuff was being left out, so that makes sense. Thanks!

I'll go ahead and attach some screenshots and revise my issue, though to be honest it was happening with nearly all of Sakura Bakushin O's training dialogues, if not all of them.
![Screenshot_20240331-121917](https://github.com/Hachimi-Hachimi/tl-en/assets/59584141/7043d676-70c6-436e-8144-284fd33d4fcc)
![Screenshot_20240331-121941](https://github.com/Hachimi-Hachimi/tl-en/assets/59584141/7b851280-1054-4473-bd52-cfeb5924dd57)
![Screenshot_20240331-122046](https://github.com/Hachimi-Hachimi/tl-en/assets/59584141/1cd44ea7-758e-4e82-9858-27e159bf4d3b)
![Screenshot_20240331-122456](https://github.com/Hachimi-Hachimi/tl-en/assets/59584141/0710f054-40e3-4dce-8344-09ca95d1dbdc)

**Comment by LeadRDRK** [comment]
Alright, I'll let this one stay as a single issue, but please, feel free to flood the issue tracker as much as you need to.

**Comment by LeadRDRK** [comment]
Resolved by https://github.com/Hachimi-Hachimi/Hachimi/commit/550adc77bee24b004053e6f4dd2da5c7f7ef7764
